name: medbert
channels:
  - HuggingFace
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - asttokens=2.1.0=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310h9128911_0
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.9.24=h5b45459_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2bbff1b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310haa95532_0
  - colorama=0.4.5=py310haa95532_0
  - cpuonly=2.0=0
  - cryptography=38.0.1=py310h21b164f_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.6.3=py310h8a704f9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fftw=3.3.9=h2bbff1b_1
  - filelock=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - huggingface_hub=0.10.1=py_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=64.2=he025d50_1
  - idna=3.4=py310haa95532_0
  - importlib-metadata=4.11.3=py310haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.17.1=pyh025b116_0
  - ipython=8.6.0=pyh08f2357_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - joblib=1.1.1=py310haa95532_0
  - jpeg=9e=h2bbff1b_0
  - jupyter_client=7.4.7=pyhd8ed1ab_0
  - jupyter_core=5.0.0=py310h5588dad_0
  - kiwisolver=1.4.4=py310h476a331_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libdeflate=1.8=h2bbff1b_5
  - libffi=3.4.2=hd77b12b_4
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.20.1=h23ce68f_0
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.4.0=h8a3f274_0
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.5.3=py310h5588dad_2
  - matplotlib-base=3.5.3=py310h7329aa0_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - numexpr=2.8.3=py310hb57aa6b_0
  - numpy=1.23.3=py310h60c9a35_0
  - numpy-base=1.23.3=py310h04254f7_0
  - openssl=1.1.1s=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.4=py310hd77b12b_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py310hdc2b20a_1
  - pip=22.2.2=py310haa95532_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - pluggy=1.0.0=pyhd8ed1ab_5
  - prompt-toolkit=3.0.32=pyha770c72_0
  - protobuf=3.20.1=py310hd77b12b_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py310haa95532_0
  - pyqt=5.9.2=py310hd77b12b_6
  - pysocks=1.7.1=py310haa95532_0
  - pytest=7.2.0=pyhd8ed1ab_2
  - python=3.10.6=hbb2ffb3_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.0=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2022.1=py310haa95532_0
  - pywin32=302=py310h2bbff1b_2
  - pyyaml=6.0=py310h2bbff1b_0
  - pyzmq=23.2.0=py310hd77b12b_0
  - qt=5.9.7=h506e8af_3
  - regex=2022.7.9=py310h2bbff1b_0
  - requests=2.28.1=py310haa95532_0
  - sacremoses=master=py_0
  - scikit-learn=1.1.2=py310h3a564e9_0
  - scipy=1.9.1=py310h86744a3_0
  - setuptools=63.4.1=py310haa95532_0
  - shellingham=1.3.1=pyhd3eb1b0_0
  - sip=4.19.13=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h2bbff1b_0
  - stack_data=0.6.1=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h2bbff1b_0
  - tokenizers=0.11.4=py310he5181cf_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=0.13.0=py310_cpu
  - torchvision=0.14.0=py310_cpu
  - tornado=6.2=py310he2412df_0
  - tqdm=4.64.1=py310haa95532_0
  - traitlets=5.5.0=pyhd8ed1ab_0
  - transformers=4.23.1=py_0
  - typer=0.4.1=py310haa95532_0
  - typing-extensions=4.3.0=py310haa95532_0
  - typing_extensions=4.3.0=py310haa95532_0
  - tzdata=2022e=h04d1e81_0
  - urllib3=1.26.12=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.6=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.8.0=py310haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
prefix: D:\Programme\miniconda3\envs\medbert
